# Ref: https://qiita.com/tomoyk/items/04d3fdafbec362f5c6db
# ブランチ名をmaster -> mainに変更
name: QiitaBackup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 00 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: npx qiita_export_all
      env:
        QIITA_ACCESS_TOKEN: ${{ secrets.QIITA_ACCESS_TOKEN }}
    - uses: EndBug/add-and-commit@v4
      with:
        add: 'items/ img/'
        author_name: 'shimajima-eiji'
        author_email: ${{ secrets.EMAIL }}
        cwd: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
