name: "push: Create _en(ja).md"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # git clone (this)

      # curlに必要なパッケージをインストール
      - name: install trans
        run: sudo apt install translate-shell

      # リポジトリ内のファイルをwebpに変換する。
      # 後で使うのでteeで結果とファイルを出力している
      - name: run curl
        run: curl -sf https://raw.githubusercontent.com/shimajima-eiji/Settings_Environment/main/for_WSL/translate.sh | sh -s -- README.md | tee translate.log
        
      # webp変換した場合のみ処理する
      - name: Commit files
        run: |
          if [ $(tail -n 1 translate.log) -ne 0 ]
          then
            rm translate.log  # 先にログファイルを消さないと、ログファイルもpushしてしまう
            git config --global user.email "${{ secrets.EMAIL }}"
            git config --global user.name "shimajima-eiji"
            git add -A
            git commit -m "[Add]Create translate file by Github Actions"
            git pull
            git push
            echo "[COMPLETE] traslated."
          else
            echo "[SKIP] No translate."
          fi        
